In [7]:
import numpy as np

In [8]:
a= np.array([[1, 2, 3, 4], [4, 6, 8, 10], [9, 11, 13, 15]])

In [9]:
a

array([[ 1,  2,  3,  4],
       [ 4,  6,  8, 10],
       [ 9, 11, 13, 15]])

In [10]:
np.gradient(a, axis=0)  # along y axis

array([[3. , 4. , 5. , 6. ],
       [4. , 4.5, 5. , 5.5],
       [5. , 5. , 5. , 5. ]])

In [11]:
np.gradient(a, axis=1)  # along x axis

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])