# Divergence result check

Theoretical example based on:

https://www.khanacademy.org/math/multivariable-calculus/multivariable-derivatives/divergence-and-curl-articles/a/divergence


## Required imports

In [21]:
from pygsf.mathematics.arrays import divergence_2D

In [22]:
from pygsf.spatial.rasters.geotransform import *

In [23]:
from pygsf.spatial.rasters.mapping import *

## Geotransform

The geotransform defines the raster-to-geographic coordinates mapping.

In [24]:
gt1 = GeoTransform(1500, 3000, 10, 10)

## Z transfer functions

These functions define the value of the cells, from the provided x and y geographic coordinates.

In [25]:
def z_func_fx(x, y):

    return 2*x - y

def z_func_fy(x, y):

    return y * y

def z_func_div(x, y):
    
    return 2 + 2*y

## Z fields (x and y components)

The gridded field values are calculated for the vector field x- and y- components, as well as the expected teorethical divergence field. 

In [26]:
rows=100; cols=50

### Vector field x-component

In [27]:
fx = array_from_function(row_num=rows, col_num=cols, geotransform=gt1, z_transfer_func=z_func_fx)

In [28]:
print(fx)

[[  15.   35.   55. ...  955.  975.  995.]
 [  25.   45.   65. ...  965.  985. 1005.]
 [  35.   55.   75. ...  975.  995. 1015.]
 ...
 [ 985. 1005. 1025. ... 1925. 1945. 1965.]
 [ 995. 1015. 1035. ... 1935. 1955. 1975.]
 [1005. 1025. 1045. ... 1945. 1965. 1985.]]


### Vector field y-component

In [29]:
fy = array_from_function(row_num=rows, col_num=cols, geotransform=gt1, z_transfer_func=z_func_fy)

In [30]:
print(fy)

[[8970025. 8970025. 8970025. ... 8970025. 8970025. 8970025.]
 [8910225. 8910225. 8910225. ... 8910225. 8910225. 8910225.]
 [8850625. 8850625. 8850625. ... 8850625. 8850625. 8850625.]
 ...
 [4100625. 4100625. 4100625. ... 4100625. 4100625. 4100625.]
 [4060225. 4060225. 4060225. ... 4060225. 4060225. 4060225.]
 [4020025. 4020025. 4020025. ... 4020025. 4020025. 4020025.]]


### Theoretical divergence

In [31]:
f_div = array_from_function(row_num=rows, col_num=cols, geotransform=gt1, z_transfer_func=z_func_div)

In [32]:
print(f_div)

[[5992. 5992. 5992. ... 5992. 5992. 5992.]
 [5972. 5972. 5972. ... 5972. 5972. 5972.]
 [5952. 5952. 5952. ... 5952. 5952. 5952.]
 ...
 [4052. 4052. 4052. ... 4052. 4052. 4052.]
 [4032. 4032. 4032. ... 4032. 4032. 4032.]
 [4012. 4012. 4012. ... 4012. 4012. 4012.]]


## Divergence result and check

Divergence as resulting from pygsf calculation:

In [33]:
div = divergence_2D(fx, fy, 10, 10)

In [34]:
print(div)

[[5992. 5992. 5992. ... 5992. 5992. 5992.]
 [5972. 5972. 5972. ... 5972. 5972. 5972.]
 [5952. 5952. 5952. ... 5952. 5952. 5952.]
 ...
 [4052. 4052. 4052. ... 4052. 4052. 4052.]
 [4032. 4032. 4032. ... 4032. 4032. 4032.]
 [4012. 4012. 4012. ... 4012. 4012. 4012.]]


In [35]:
np.allclose(f_div, div)

True