### Magnitude gradient along flowlines

In [37]:
import math

In [38]:
import numpy as np

In [50]:
from pygsf.spatial.rasters.fields import *

## Test 1

In [40]:
fx = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

In [41]:
fx

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
fy = np.array([
    [2,2,2],
    [2,2,2],
    [2,2,2]
])

In [43]:
magn = magnitude(fx, fy)

In [44]:
magn

array([[2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798]])

In [45]:
sqrt(1 + 2**2)

2.23606797749979

In [46]:
oriens_d = orients_d(fx, fy)

In [47]:
oriens_d

array([[26.56505118, 26.56505118, 26.56505118],
       [26.56505118, 26.56505118, 26.56505118],
       [26.56505118, 26.56505118, 26.56505118]])

In [48]:
degrees(math.atan(0.5))

26.56505117707799

In [49]:
magn_grad_along_flowlines(fx, fy, 10, 10)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

The previous result is correct.

## Test 2

In [96]:
fx = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

In [97]:
fy = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

In [98]:
oriens_d = orients_d(fx, fy)

In [99]:
oriens_d

array([[90., 90., 90.],
       [90., 90., 90.],
       [90., 90., 90.]])

In [100]:
magnitude(fx, fy)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [101]:
np.sqrt(fx**2 + fy**2)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [102]:
magn_grad_along_flowlines(
        fld_x=fx,
        fld_y=fy,
        cell_size_x=10,
        cell_size_y=10) 

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [103]:
orien_rad = orients_r(fx, fy)

In [104]:
dm_dx, dm_dy = magn_grads(
    fld_x=fx,
    fld_y=fy,
    dir_cell_sizes=[1, 1])    

In [105]:
dm_dx

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
dm_dy

array([[-0., -0., -0.],
       [-0., -0., -0.],
       [-0., -0., -0.]])

In [108]:
velocity_gradient = dm_dx * np.sin(orien_rad) + dm_dy * np.cos(orien_rad)

In [109]:
velocity_gradient

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Results correct.

## Test 3

In [119]:
fx = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

In [121]:
fy = -fx

In [122]:
magn = magnitude(fx, fy)

In [123]:
magn

array([[1.41421356, 2.82842712, 4.24264069],
       [2.82842712, 4.24264069, 5.65685425],
       [4.24264069, 5.65685425, 7.07106781]])

In [115]:
oriens_d = orients_d(fx, fy)

In [117]:
oriens_d

array([[135., 135., 135.],
       [135., 135., 135.],
       [135., 135., 135.]])

In [124]:
magn_grad_along_flowlines(
        fld_x=fx,
        fld_y=fy,
        cell_size_x=1,
        cell_size_y=1) 

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

Cell (0,0) vs. cell (1,1):

sqrt(2) vs. 3 sqrt(2)

dist = sqrt(2)

gradient = (3sqrt(2) - sqrt(2))/sqrt(2) = 2

Result is correct.

In [126]:
magn_grad_along_flowlines(
        fld_x=fx,
        fld_y=fy,
        cell_size_x=10,
        cell_size_y=10) 

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

Result is correct.